add signatures

diff --git a/keys/decrypt-all b/keys/decrypt-all
--- a/keys/decrypt-all
+++ b/keys/decrypt-all
@@ -1,10 +1,16 @@
 if ! [ -d "keys" ]; then echo "no keys dir"; exit 1; fi
 if ! [ -f "keys/privatekey" ]; then echo "no privatekey"; exit 1; fi
+if ! [ -f "keys/publickey" ]; then echo "no publickey"; exit 1; fi
 if ! [ -f "keys/iv" ]; then echo "no iv"; exit 1; fi
 for f in $(find . -type f -not -path "*/keys/*" -not -path "*/.git/*" | grep .enc); do
 	_fn="$(echo $f | sed 's/\.enc$//g')"
+	bi verify $f.sig $f keys/publickey
+	if [ $? -ne 0 ]; then
+		echo "failed to validate signature on $f"
+		exit 1
+	fi
 	openssl enc -a -chacha -salt -K $(cat keys/privatekey) -iv $(cat keys/iv) -d -in $f -out $_fn
 	chmod +x $_fn
-	rm -rf $f
+	rm -rf $f $f.sig
 done
 
